version: 2
registries:
  kg-tfe-registry: # Define access for a private registry, https://github.com/github/docs/pull/6808
    type: terraform-registry
    url: https://tfe.karla-gabriel.sbx.hashidemos.io
    token: ${{secrets.TF_API_TOKEN_DEPENDABOT}}

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    registries:
      - kg-tfe-registry
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"