name: Format Code

on:
  pull_request

permissions:
  contents: write

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.AUTO_COMMIT_TOKEN }}
      - name: Setup Terraform
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
      - name: Format Code
        run: |
          terraform fmt -recursive .
      - name: Commit Format Changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add .
          git diff-index --quiet HEAD || git commit -m "fix: Auto format codebase"
          git push